### ISSUE TITLE
API for getting user profile data

### ISSUE THREAD

**Issue by syedautherabbas** [100DaysOfCloud/100DaysOfCloudBackend#2]

**Comment by syedautherabbas** [comment]
Please review https://github.com/100DaysOfCloud/100DaysOfCloudBackend/pull/3

**Comment by what-name** [comment]
PR merged but not functional yet. Leave open

**Comment by what-name** [comment]
Waiting for merge with #5 
- the test for the Lambda code is incorrect (it's testing itself instead of the Lambda function). 
- That PR has a lot of other things incorporated. Once the Lambda code and folder structure gets improved, the PR can be merged and it the API will get deployed automatically.

**Comment by syedautherabbas** [comment]
Do the comments still apply or is you only meant to highlight that comments might get resolved with #5 ?

**Comment by what-name** [comment]
Continued in #18
