### ISSUE TITLE
Set up CI pipeline for automated testing before PR can be merged

### ISSUE THREAD

**Issue by antoniolofiego** [100DaysOfCloud/100DaysOfCloudBackend#4]
We should set up a pipeline that builds/tests our commits before they can be merged.
Optimal implementation:
https://github.com/bayko/codebuild-github-ci

**Comment by what-name** [comment]
### Notes
This CI pipeline is different from the deployment pipeline. This is only for automated testing when a PR gets opened. See the screenshot below.

![unknown](https://user-images.githubusercontent.com/20590073/89188229-a8b1e000-d59e-11ea-93b1-3d2f6205056e.png)

This is the desired end result, to have tests run automatically on the PR itself before it even gets merged, so that we can see if it'll work or not at all. This can be done via the above mentioned link/project by Bayko, or a GitHub Actions workflow as well. Personally I think the GitHub Actions workflow would be much better as it's much simpler and doesn't require outside communication to any AWS resources. Running the tests in a Action is pretty easy, redirecting the results back is what I'm not sure on how to do, that's where help is needed. Of course if the tests fail, merging must not be allowed.

The current tests can be seen in the `sam/api` folder. They are written with `PyTest` and should be easy to execute all at once thanks to PyTest's "run all tests in this folder" functionality (I'm butchering it but that's the basic premise). The test for the very first `(test_)get_user_by_id.py`is not functional currently because it is testing itself instead of the Lambda function's code, it needs to be fixed as well (fyi) - #3 is responsible for that.

The current active branch is `dev`, but once a functional PR testing GitHub Action is written, it can be ported to other branches (`staging`, `main`) as well with ease.

**Comment by what-name** [comment]
Testing started with #8 

Improving local testing strategy can only happen after the contents of the `sam/api` folder are improved. Closing for now and opening new ticket for that #18
